language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3.5"

os: linux
sudo: required

# command to install dependencies
install:
  - sudo apt-get install redis-server
  - python setup.py install

before_script:
  - sudo redis-server &

# command to run tests
script:
  # - less strict time limit, set to 30 minutes
  - travis_wait 30 nosetests . -v
  # - pytest

notifications:
email: false
